name: appstore

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  appstore_dev:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.7
      run: sudo xcode-select --switch /Applications/Xcode_11.7.app

    - name: Installs librsvg
      run: brew install librsvg

    - name: Installs magick
      run: brew install imagemagick

    - name: Sets up bundler
      run: bundle update --bundler
      
    - name: Build and Sign
      env:
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
        APP_SCHEME: "Release-Dev"
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_DEV }}
        FASTLANE_TEAM_ID: ${{ secrets.TEAM_ID }}
        BADGE_TITLE: "DEV"
      run: bundle exec fastlane build_and_sign

    - name: SHA256
      run: shasum -a 256 build/N2Step.ipa

    - name: Archive ipa file
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_DEV_N2Step.ipa
        path: build/N2Step.ipa
    
    - name: Archive xcarchive (incl symbols) files
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_DEV_N2Step.xcarchive
        path: "build/N2Step.xcarchive"
    
    - name: Archive log file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_DEV_Build.log
        path: "build/build.log"


  appstore_prod:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode 11.7
      run: sudo xcode-select --switch /Applications/Xcode_11.7.app
    
    - name: Sets up bundler
      run: bundle update --bundler
    
    - name: Build and Sign
      env:
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
        APP_SCHEME: "Release-Prod"
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER_PROD }}
        FASTLANE_TEAM_ID: ${{ secrets.TEAM_ID }}
        SKIP_ADD_BADGE: true
        BADGE_TITLE: ""
      run: bundle exec fastlane build_and_sign

    - name: SHA256
      run: shasum -a 256 build/N2Step.ipa

    - name: Archive ipa file
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_PROD_N2Step.ipa
        path: build/N2Step.ipa
    
    - name: Archive xcarchive (incl symbols) files
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_PROD_N2Step.xcarchive
        path: "build/N2Step.xcarchive"
    
    - name: Archive log file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: AppStore_PROD_Build.log
        path: "build/build.log"
